### PR TITLE
Fix error when user put invalid ownerInvestment value

### LINKED ISSUE #179: BoundExceededError
hi,
i type something wrong and this happens : 

BoundExceededError
"participationSum + ownerPreparation" should not be > than 330 for parameters "participationSum" and "ownerPreparation" of ComputeLevelInvestment(levelCost, currentDeposits, yourParticipation, otherParticipation, yourArcBonus, fpTargetReward)

i can go back to basic side (babel) but this error still stand there when i open the page again,
reload this page does not fix it

mfg

### PR DESCRIPTION
**Pull request by Heziode**
Fix #179

### CODE REVIEW

**Comment by DaEgo** [comment]
Hi,

works fine and page works again :-)

maybe just for the look a suggestion,

can u change the color of the FP bar from green to maybe red/blink,

when there are more FPs in the building as possible, so i can see "oh damn i made a error" ?

i know thats not so important, but maybe if u have a idea how to and some time, some day...    ;-)

 

mfg

Chris

 

Gesendet: Donnerstag, 14. März 2019 um 21:32 Uhr
Von: "Quentin Dauprat" <notifications@github.com>
An: "FOE-Tools/FOE-Tools.github.io" <FOE-Tools.github.io@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [FOE-Tools/FOE-Tools.github.io] Fix error when user put invalid ownerInvestment value (#180)


Fix #179


You can view, comment on, or merge this pull request online at:

  https://github.com/FOE-Tools/FOE-Tools.github.io/pull/180

Commit Summary


	fix(gb-investment): fix error when user put invalid ownerInvestment value
	chore(contributors): update page


File Changes


	M CONTRIBUTORS.md (2)
	M all-contributorsrc.json (9)
	M components/gb-investment/script.js (13)
	M components/gb-investment/template.pug (10)
	M test/unit/components/gb-investment.js (15)


Patch Links:


	https://github.com/FOE-Tools/FOE-Tools.github.io/pull/180.patch
	https://github.com/FOE-Tools/FOE-Tools.github.io/pull/180.diff

**Comment by Heziode** [comment]
@DaEgo,

Do you mean add a green highlight when the content are valid, and red when it's invalid ?

**Comment by DaEgo** [comment]
The green Bar dont need to blik if everything is fine,

but u give me a idea, maybe :

 

yellow (no blink) if next free slot is not safe

green (no blink) if next free slot is safe

red (blink!) when noobs like me add to many FP and calculation is wrong

 

what u think ?!

 

Gesendet: Donnerstag, 14. März 2019 um 21:43 Uhr
Von: "Quentin Dauprat" <notifications@github.com>
An: "FOE-Tools/FOE-Tools.github.io" <FOE-Tools.github.io@noreply.github.com>
Cc: Chris <daego@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [FOE-Tools/FOE-Tools.github.io] Fix error when user put invalid ownerInvestment value (#180)


@DaEgo,

Do you mean add a green highlight when the content are valid, and red when it's invalid ?

**Comment by Heziode** [comment]
This is not the goal of this PR.
But it can be considerated.
We will continue this conversation in email, and we will purpose that to the community before release that to prevent the Card feature flop/nightmare 😂

**Pull request merged**
