### PR TITLE
Correction of Contributors

### PR DESCRIPTION
**Pull request by FJduFou**
**Addition of:**
Avatar: "https://foe.tools/img/icons/logo.png" for contributors who no longer exist
Avatar: "https://forum.en.forgeofempires.com/styles/game/avatars/avatar.png" for contributors who have no avatar defined on the forum

**Removal of:**
Broken link to contributors

**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by FJduFou** [comment]
You need rebuild the **CONTRIBUTORS.md** after merge this PR, sorry 😁

**Review by Heziode — CHANGES_REQUESTED** [review]
Use of [Forum default avatar](https://forum.en.forgeofempires.com/styles/game/avatars/avatar.png) for every contributors that do not have a custom avatar.

**Review by Heziode — CHANGES_REQUESTED** [review]
Generate the **CONTRIBUTORS.md** with `npm run contributors:generate`

**Comment by FJduFou** [comment]
_When there is no link, this does not mean that it no longer exists_
For this, I have use: "https://foe.tools/img/icons/logo.png", i change for: "https://forum.en.forgeofempires.com/styles/game/avatars/avatar.png"?

**Comment by Heziode** [comment]
> _When there is no link, this does not mean that it no longer exists_
> For this, I have use: "https://foe.tools/img/icons/logo.png", i change for: "https://forum.en.forgeofempires.com/styles/game/avatars/avatar.png"?

This link: https://forum.en.forgeofempires.com/styles/game/avatars/avatar.png
(And don't forgot to regenerate the CONTRIBUTORS.md after updating avatar)

**Comment by FJduFou** [comment]
Ok now? 😅

**Review by Heziode — APPROVED** [review]

**Comment by Heziode** [comment]
Yes is good :)

Thank you !

it will be in the next release, that should be published the next sunday.

**Comment by FJduFou** [comment]
Ok, so I have the time to make many more small changes

**Pull request merged**
