### PR TITLE
Updating the scrollbar

### PR DESCRIPTION
**Pull request by FJduFou**
**Before:**
image
**After:**
image
**Note:** This effect does not apply to Firefox based browser, they will keep the old appearance ...

### CODE REVIEW

**Comment by FJduFou** [comment]
I made sure that there is **no need to change** the colors for dark / light
**Light:** better visibility
**Dark:** better immersion

_You can still change if you want_

**Comment by Heziode** [comment]
I do not agree this change.

Even if it's cool to change it's style, the scrollbar shall remain unchanged to keep the best user experience as possible.

By keeping the OS/Browser default style for scroolbar, the user is not lost/stressed because he/she is using it during its daily navigation.

**Comment by FJduFou** [comment]
To each his own vision of the thing... 😣

**Comment by FJduFou** [comment]
This is precisely the problem with many things in the digital world, we can make lots of visual improvements everywhere, that would be wonderful, but we still have the same problem: the fear of breaking habits ...
Example: the Windows UI, we end up with icons that are updated 1 by 1 (Fluent Design) so as not to rush users to a change ... I find it sad, we end up with a huge amount ugly things for a few people who don't want to see things evolve ...
I think we have to take the step ... That was my point of view ...

**Comment by Heziode** [comment]
Good point of view.

I think we can put it back on the table when I will have finished the migration to the new CSS framework.

Keep in mind: FOE-Tools is played by a large panel of users. A large proportion of these users are over the age of 45-50. So I can't change the whole IU at once, I've already tried, I've been destroyed by this part of the community.

To sum up, your idea and point of view are interesting, and it is not incompatible with the future of FOE-Tools. But currently, I will progressively update the UI from Bulma to Tailwind, with some improvements of the UI/UX, and after that, we will be able to see how to integrate this improvement.

**Comment by FJduFou** [comment]
This is precisely the problem with many things in the digital world, we can make lots of visual improvements everywhere, that would be wonderful, but we still have the same problem: the fear of breaking habits ...
Example: the Windows UI, we end up with icons that are updated 1 by 1 (Fluent Design) so as not to rush users to a change ... I find it sad, we end up with a huge amount ugly things for a few people who don't want to see things evolve ...
I think we have to take the step ... That was my point of view ...
Could we speak privately about this migration, I would like to know some details please?

**Comment by Heziode** [comment]
> Could we speak privately about this migration, I would like to know some details please?

Of course, you can find my mail on [my profile](https://github.com/Heziode).

**Pull request closed without merging**
